### ISSUE TITLE
Clear all previous votes / reset votes

### ISSUE THREAD

**Issue by sjhale** [tatablack/leaner-coffee-powerup#14]
Thanks for building this powerup, it's very useful! This is a enhancement request, instead of a bug. 

It would be great if there was an option to clear all existing votes on the cards, rather than having to rely on every person individually undoing their previous votes from a previous lean coffee session at the start of a new lean coffee session. 

I'm aware that technically there shouldn't be any leftover cards from a previous session, but in practice, for some of our lean coffee sessions, we find that instead of deleting the existing list of cards and starting completely afresh, it is more efficient to leave the previous cards in place, reset the votes, and use the new votes to set the agenda for the current session.

**Comment by tatablack** [comment]
Hi, @sjhale 🙂 I imagine this would make sense at the list level (rather than the whole board), so you could keep seeing the votes on the cards that were actually discussed). WDYT?

It makes sense as a use case, I'd say. It shouldn't be too hard to implement, but I'll need to check. Thanks for the feedback!

**Comment by sjhale** [comment]
@tatablack I can't believe how quickly you incorporated this! Thanks very much - it's exactly what I was after! :)
