### ISSUE TITLE
Extract strings for internationalization

### ISSUE THREAD

**Issue by alisonatwork** [tatablack/leaner-coffee-powerup#20]
Right now many of the strings are hard-coded (e.g. Vote and Discussion buttons).

If these strings are extracted to a central string store, they will be easier to translate.

I think we might be able to get the Trello language from `lang` cookie on `trello.com`, but if that's not accessible to powerups, we could still use the browser language to try localize.

**Comment by tatablack** [comment]
Sounds like a good idea.. 👍 Looking at the docs, there's this, so it may be relatively straightforward: https://developers.trello.com/reference/#localization

Since it involves a refactor, it may make sense for me to finally write some tests for the power-up, first 🙂 While there has been a lot of manual testing in the past (which made me confident enough to release it), having to do regression testing for every change does not scale, obviously.

Thanks for the suggestion!
