### ISSUE TITLE
Stickie-sized character limit

### ISSUE THREAD

**Issue by sconesoft-brendan** [tatablack/leaner-coffee-powerup#30]
3M Post-Its©®™ being only so big (especially when written on with markers instead of pens) provides creative constraint for topics to be clear & succinct.  Trello cards though... _**have** no constraint._ 

Lean Coffee™'s structure gets unwieldy and less democratic when someone can go full "When the Pawn Hits the Conflicts He Thinks like a King What He Knows Throws the Blows When He Goes to the Fight and He'll Win the Whole Thing 'fore He Enters the Ring There's No Body to Batter When Your Mind Is Your Might so When You Go Solo, You Hold Your Own Hand and Remember That Depth Is the Greatest of Heights and If You Know Where You Stand, Then You Know Where to Land and If You Fall It Won't Matter, Cuz You'll Know That You're Right, frequently abridged to When the Pawn..., is the second studio album by American singer-songwriter Fiona Apple." and crowd out the whole list during voting.

**Comment by tatablack** [comment]
Thanks for the suggestion 🙂

Unfortunately, I don't think there's a way for a power-up to enforce a character limit - I've taken a quick look in the Atlassian forums, and the only reference I can see is to cases where a *very long* text was not saved (we're talking more than 16k worth of description) - which may just be an API limit.

If you want to double-check, here's a link to the official forums: https://community.atlassian.com/t5/Trello-questions/qa-p/trello-questions

I've also checked whether this is something that could be achieved with Butler - since it was acquired by Trello, it's enabled by default for everyone, and it does have automation capabilities: it can react to triggers like, say, a card's description being created or updated.

Unfortunately again, while it allows creating a trigger when a description contains certain words, there's no trigger on size. You may certainly create a feature request, using their "Feedback" button, in the lower left corner of the Butler UI.

Apologies, though, as I realise none of this solves your problem 😬

**Comment by sconesoft-brendan** [comment]
Thanks for digging into all that! Sometimes problems can be solved in software, sometimes in wetware. It can be an instruction to participants and managed with facilitator feedback.
